### ISSUE TITLE
F Tuned Version/Additional Warning?

### ISSUE THREAD

**Issue by CandyAngel** [yonah-ag/musescore-recorder-fingering#1]
Heyas,

Thanks so much for making this plugin. It seems like it would be very helpful!

Would you consider adding an option for F-tuned recorders (sorry if my terminology is wrong/messy, I'm new to recorders) such as the Alto(Treble)? No prizes for guessing which recorder I'm starting with! :)

Also, as a new user to the plugin, I was initially confused by it only adding the fingerings for "A" and that was with all holes covered, which I knew was wrong. Looking at the QML code, I guessed the pitch->ASCII conversion wasn't working correctly, which helped me figure out that it doesn't work if the instrument isn't set to "Recorder". Maybe it is worth adding a warning in that case or perhaps more generally, if a lot of notes fall outside of the expected ASCII range?

**Comment by yonah-ag** [comment]
Thanks for the feedback. I am not that familiar with recorders but I am learning how to write plugins so this project looked ideal.

If you could send me details of fingerings for different recorders then I will add them.

Are all the existing fingerings correct when within the recorder's range? If not I will fix those too. I don't think that the instrument setting should affect this as the plugin only looks at the actual notes, irrespective of whatever instrument is present.

**Comment by CandyAngel** [comment]
Ah okay. From what I understand, there are mainly 4 types of recorder: C-Baroque, C-German, F-Baroque, F-German which have differing fingerings. I will put together what I know/can find about this for you to consider adding.

I think the issue with adding the notes and only "A" showing up might be more user-error and/or lack of understanding than anything. While the notes visually looked like they would be in range (as in, on the stave), having the wrong instrument selected made the actual pitch outside of "recorder range". Annoyingly, I can't replicate what I got previously with the "A", so maybe I did something very wrong! :)

This is what I mean by them looking visually similar, but being different due to "having the wrong instrument" for the plugin to work correctly.

![image](https://user-images.githubusercontent.com/9965206/159498485-d80e2142-259a-4cdd-ab0f-76f67e9d8cb9.png)

**Comment by yonah-ag** [comment]
I see what you mean about the instruments. The difference appears to be connected to the clefs. The recorder clef has a small 8 above it and the finger symbols for the violin stave are offset by 8 notes, so this may well be the reason. Perhaps the recorder is a transposing instrument and that what appears to be middle-C is actually an octave higher, where the finger symbols start for violin.

**Comment by yonah-ag** [comment]
I have asked on the MuseScore forum:
https://musescore.org/en/node/329101#comment-1120920

**Comment by yonah-ag** [comment]
It is indeed because the recorder is a 'transposing' instrument. It is typically notated an octave below its actual sounding pitch. Violin is non-transposing and its range extends below middle C, (C4), whereas the soprano recorder only reaches C5.

I will add some info to the plugui's documentation to explain this. Thanks for bringing it to my attention.
